AllCops:
  DisplayCopNames: true

#
# Style
#

LineLength:
  Max: 128

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

#
# Metrics
#

Metrics/MethodLength:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  Enabled: false

#
# Lint
#

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowedException:
  Enabled: false
