AllCops:
  DisplayCopNames: true

#
# Style
#

LineLength:
  Max: 128

Style/AccessorMethodName:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

#
# Metrics
#

Metrics/AbcSize:
  Max: 50

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

#
# Lint
#

Lint/HandleExceptions:
  Enabled: false

Lint/ShadowedException:
  Enabled: false
